/**
 * Blog article generation pipeline.
 * Generates SEO-optimized articles using Gemini, with cover images.
 */

import { prisma } from '@/lib/db';
import { GoogleGenerativeAI } from '@google/generative-ai';
import { SAFETY_SETTINGS } from '@/lib/generation/shared/safety';
import { TOPIC_POOL, INTERNAL_LINKS, type TopicTemplate } from './topics';

/**
 * Pick the next topic to write about.
 * Strategy: find the keyword with the fewest recent posts, then pick an unused topic.
 */
async function pickTopic(): Promise<TopicTemplate> {
  // Get existing post titles and keyword counts
  const existingPosts = await prisma.blogPost.findMany({
    select: { title: true, primaryKeyword: true },
  });

  const existingTitles = new Set(existingPosts.map(p => p.title.toLowerCase()));

  // Count posts per keyword
  const keywordCounts: Record<string, number> = {};
  for (const post of existingPosts) {
    keywordCounts[post.primaryKeyword] = (keywordCounts[post.primaryKeyword] || 0) + 1;
  }

  // Find unused topics, sorted by keyword with fewest posts
  const unusedTopics = TOPIC_POOL.filter(
    t => !existingTitles.has(t.title.toLowerCase())
  );

  if (unusedTopics.length === 0) {
    // All topics used - pick the least-used keyword and generate a fresh angle
    const leastUsedKeyword = Object.entries(keywordCounts)
      .sort((a, b) => a[1] - b[1])[0]?.[0] || TOPIC_POOL[0].primaryKeyword;

    return {
      primaryKeyword: leastUsedKeyword,
      title: '', // Will be generated by AI
      category: 'guides',
      angle: 'fresh perspective with new insights',
    };
  }

  // Sort by keyword count (ascending) to prioritize underrepresented keywords
  unusedTopics.sort((a, b) => {
    const countA = keywordCounts[a.primaryKeyword] || 0;
    const countB = keywordCounts[b.primaryKeyword] || 0;
    return countA - countB;
  });

  return unusedTopics[0];
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .substring(0, 80);
}

/**
 * Simple markdown to HTML conversion (no external deps needed).
 */
function markdownToHtml(md: string): string {
  let html = md
    // Code blocks first (before other processing)
    .replace(/```(\w+)?\n([\s\S]*?)```/g, '<pre><code>$2</code></pre>')
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    // Headers
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    // Bold and italic
    .replace(/\*\*\*(.+?)\*\*\*/g, '<strong><em>$1</em></strong>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    // Links
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>')
    // Unordered lists
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    // Ordered lists
    .replace(/^\d+\. (.+)$/gm, '<li>$1</li>')
    // Horizontal rules
    .replace(/^---$/gm, '<hr>')
    // Blockquotes
    .replace(/^> (.+)$/gm, '<blockquote>$1</blockquote>');

  // Wrap consecutive <li> items in <ul>
  html = html.replace(new RegExp('(<li>.*?</li>\\n?)+', 'gs'), (match) => `<ul>${match}</ul>`);

  // Paragraphs - wrap remaining lines
  html = html
    .split('\n\n')
    .map(block => {
      const trimmed = block.trim();
      if (!trimmed) return '';
      if (trimmed.startsWith('<h') || trimmed.startsWith('<ul') || trimmed.startsWith('<ol') ||
        trimmed.startsWith('<pre') || trimmed.startsWith('<blockquote') || trimmed.startsWith('<hr')) {
        return trimmed;
      }
      return `<p>${trimmed.replace(/\n/g, ' ')}</p>`;
    })
    .join('\n');

  return html;
}

/**
 * Inject internal links into HTML content.
 * Only links the first occurrence of each phrase.
 */
function injectInternalLinks(html: string): string {
  const linkedPhrases = new Set<string>();

  for (const [phrase, url] of Object.entries(INTERNAL_LINKS)) {
    if (linkedPhrases.has(url)) continue; // One link per URL

    // Case-insensitive match, first occurrence only, not already inside a tag
    const regex = new RegExp(`(?<![>/"'])\\b(${phrase.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')})\\b(?![^<]*>)`, 'i');
    const match = html.match(regex);
    if (match && match.index !== undefined) {
      html = html.substring(0, match.index) +
        `<a href="${url}">${match[1]}</a>` +
        html.substring(match.index + match[1].length);
      linkedPhrases.add(url);
    }
  }

  return html;
}

/**
 * Generate article content using Gemini.
 */
async function generateContent(topic: TopicTemplate, existingTitles: string[]): Promise<{
  title: string;
  content: string;
  metaDescription: string;
  excerpt: string;
  keywords: string[];
}> {
  const existingList = existingTitles.length > 0
    ? `\nDo NOT write about these topics that already exist:\n${existingTitles.slice(-20).map(t => `- ${t}`).join('\n')}\n`
    : '';

  const titleInstruction = topic.title
    ? `Use this title: "${topic.title}"`
    : `Create an SEO-optimized title targeting the keyword "${topic.primaryKeyword}"`;

  const prompt = `You are a content writer for DraftMyBook, an AI-powered book creation platform. Write a blog article.

${titleInstruction}
Primary keyword: "${topic.primaryKeyword}"
Article angle: ${topic.angle}
Category: ${topic.category}
${existingList}

REQUIREMENTS:
1. Write 1200-1800 words in markdown format
2. Include the primary keyword naturally 3-5 times (don't force it)
3. Use H2 and H3 headings to structure the content
4. Include practical, actionable advice with specific examples
5. Mention DraftMyBook naturally 2-3 times as a tool that can help (not salesy)
6. Write in a conversational, helpful tone - like advising a friend
7. Include bullet lists where appropriate
8. End with a conclusion that encourages action

DO NOT:
- Write generic filler content
- Stuff keywords unnaturally
- Sound like a sales pitch
- Use AI cliches ("in today's fast-paced world", "delve into", "leverage")
- Use the word "robust", "landscape", "tapestry", or "journey"

OUTPUT FORMAT (follow exactly):
---TITLE---
The article title here
---META---
A 150-160 character meta description targeting the primary keyword
---EXCERPT---
A 150-160 character excerpt for the blog listing
---KEYWORDS---
keyword1, keyword2, keyword3, keyword4, keyword5
---CONTENT---
The full article in markdown format`;

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) throw new Error('GEMINI_API_KEY not set');
  const genAI = new GoogleGenerativeAI(apiKey);
  const model = genAI.getGenerativeModel({
    model: 'gemini-3.1-pro-preview',
    safetySettings: SAFETY_SETTINGS,
  });

  const result = await model.generateContent({
    contents: [{ role: 'user', parts: [{ text: prompt }] }],
    generationConfig: {
      temperature: 0.8,
      maxOutputTokens: 8192,
    },
  });

  const response = result.response.text();

  // Parse sections
  const titleMatch = response.match(/---TITLE---\s*([\s\S]*?)---META---/);
  const metaMatch = response.match(/---META---\s*([\s\S]*?)---EXCERPT---/);
  const excerptMatch = response.match(/---EXCERPT---\s*([\s\S]*?)---KEYWORDS---/);
  const keywordsMatch = response.match(/---KEYWORDS---\s*([\s\S]*?)---CONTENT---/);
  const contentMatch = response.match(/---CONTENT---\s*([\s\S]*?)$/);

  const title = titleMatch?.[1]?.trim() || topic.title || `Guide to ${topic.primaryKeyword}`;
  const metaDescription = metaMatch?.[1]?.trim().substring(0, 160) || `Learn about ${topic.primaryKeyword} with DraftMyBook.`;
  const excerpt = excerptMatch?.[1]?.trim().substring(0, 160) || metaDescription;
  const keywords = keywordsMatch?.[1]?.trim().split(',').map(k => k.trim()).filter(Boolean) || [topic.primaryKeyword];
  const rawContent = contentMatch?.[1]?.trim() || '';

  // Convert markdown to HTML and inject internal links
  let htmlContent = markdownToHtml(rawContent);
  htmlContent = injectInternalLinks(htmlContent);

  return { title, content: htmlContent, metaDescription, excerpt, keywords };
}

/**
 * Generate a cover image for the article.
 */
async function generateCoverImage(title: string, primaryKeyword: string): Promise<{
  imageUrl: string;
  altText: string;
} | null> {
  try {
    // Shorten title for cover if too long
    const coverTitle = title.length > 60 ? title.substring(0, 57) + '...' : title;

    const prompt = `Create a professional magazine-style blog cover image.

LAYOUT:
- 16:9 landscape format
- The title text "${coverTitle}" must appear prominently on the image
- Title should be in bold, clean, modern typography (white or light text)
- Place title in the lower-third or center of the image with enough contrast to read
- Add a small "DraftMyBook" watermark/logo text in one corner (subtle, small)

VISUAL STYLE:
- Modern, editorial design like a tech magazine or Medium article cover
- Rich, atmospheric background related to: ${primaryKeyword}
- Use depth of field, gradients, or overlays to ensure text readability
- Color palette: deep blues, purples, or warm tones with bright accents
- Professional quality, suitable for a blog header

SUBJECT MATTER:
- Conceptual imagery related to books, writing, AI, creativity
- Could include: open books, glowing screens, pen/paper, abstract AI patterns
- The imagery should SUPPORT the title, not compete with it

The text MUST be clearly legible and spelled correctly.`;

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) throw new Error('GEMINI_API_KEY not set');
    const genAI = new GoogleGenerativeAI(apiKey);
    const imageModel = genAI.getGenerativeModel({
      model: 'gemini-3-pro-image-preview',
      safetySettings: SAFETY_SETTINGS,
    });

    const result = await imageModel.generateContent(prompt);

    const parts = result.response.candidates?.[0]?.content?.parts;
    if (parts) {
      for (const part of parts) {
        const inlineData = (part as { inlineData?: { mimeType: string; data: string } }).inlineData;
        if (inlineData?.data) {
          return {
            imageUrl: `data:${inlineData.mimeType};base64,${inlineData.data}`,
            altText: `Cover illustration for: ${title}`,
          };
        }
      }
    }

    console.warn('[Blog] Cover image generation returned no image data');
    return null;
  } catch (error) {
    console.error('[Blog] Failed to generate cover image:', error);
    return null; // Non-critical - article can exist without cover
  }
}

/**
 * Main entry point: generate and publish a new blog article.
 */
export async function generateAndPublishArticle(): Promise<{
  success: boolean;
  slug?: string;
  title?: string;
  error?: string;
}> {
  try {
    console.log('[Blog] Starting article generation...');

    // 1. Pick topic
    const topic = await pickTopic();
    console.log(`[Blog] Selected topic: "${topic.title || topic.primaryKeyword}" (${topic.category})`);

    // 2. Get existing titles for deduplication
    const existing = await prisma.blogPost.findMany({ select: { title: true } });
    const existingTitles = existing.map(p => p.title);

    // 3. Generate content
    const { title, content, metaDescription, excerpt, keywords } = await generateContent(topic, existingTitles);
    console.log(`[Blog] Generated article: "${title}" (${content.length} chars)`);

    // 4. Generate slug and ensure uniqueness
    let slug = slugify(title);
    const existingSlug = await prisma.blogPost.findUnique({ where: { slug } });
    if (existingSlug) {
      slug = `${slug}-${Date.now().toString(36)}`;
    }

    // 5. Generate cover image
    const cover = await generateCoverImage(title, topic.primaryKeyword);
    console.log(`[Blog] Cover image: ${cover ? 'generated' : 'skipped'}`);

    // 6. Calculate reading time (~200 words per minute)
    const wordCount = content.replace(/<[^>]+>/g, '').split(/\s+/).length;
    const readingTime = Math.max(1, Math.ceil(wordCount / 200));

    // 7. Save to database
    const post = await prisma.blogPost.create({
      data: {
        title,
        slug,
        content,
        excerpt,
        metaDescription,
        keywords,
        primaryKeyword: topic.primaryKeyword,
        coverImageUrl: cover?.imageUrl || null,
        coverImageAlt: cover?.altText || null,
        category: topic.category,
        readingTime,
        published: true,
        publishedAt: new Date(),
      },
    });

    console.log(`[Blog] Published: "${title}" at /blog/${slug}`);
    return { success: true, slug: post.slug, title: post.title };
  } catch (error) {
    const msg = error instanceof Error ? error.message : 'Unknown error';
    console.error('[Blog] Article generation failed:', msg);
    return { success: false, error: msg };
  }
}
